apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "privategpt-react.fullname" . }}
  labels: {{- include "privategpt-react.labels" . | nindent 4 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "privategpt-react.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "privategpt-react.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
