apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "privategpt-react.fullname" . }}
  labels: {{ - include "privategpt-react.labels" . | nindent 4 }}
rules:
    - apiGroups:
        - privategpt.eirl
      resources:
        - privategptinstances
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - privategpt.eirl
      resources:
        - privategptinstances/finalizers
      verbs:
        - update
    - apiGroups:
        - privategpt.eirl
      resources:
        - privategptinstances/status
      verbs:
        - get
        - patch
        - update
